[package]
name = "lean-matrix-cookbook"
version = "0.1"
lean_version = "leanprover-community/lean:3.50.3"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "cb9077f70849a93b19e01903d497029014d76e35"}
